import type { Metadata } from "next";
import Link from "next/link";
import { microgridTypes } from "../../data/content";
import { siteContact } from "../../data/site";

export const metadata: Metadata = { title: "Types of Microgrids: A Practical Guide", description: "Compare campus, community, island, remote, military, industrial, DC, and utility microgrids with clear definitions and examples.", alternates: { canonical: "/guides/types-of-microgrids" } };

const questions = [
  { q: "What are the main types of microgrids?", a: "Common types include campus, community, island, remote, military, industrial, direct-current, and utility microgrids. A single project can fit more than one category." },
  { q: "What is the difference between an island microgrid and islanding?", a: "An island microgrid serves a geographically isolated place. Islanding is an operating mode in which any grid-connected microgrid disconnects from the wider power system and runs independently." },
  { q: "Do all microgrids use renewable energy?", a: "No. A microgrid is defined by coordinated local control and the ability to serve a bounded set of loads. Its resources may include solar, wind, batteries, CHP, fuel cells, diesel, or the utility grid." },
];

export default function TypesGuidePage() {
  const schema = { "@context": "https://schema.org", "@type": "Article", headline: "Types of Microgrids: A Practical Guide", author: { "@type": "Organization", name: siteContact.organization, url: siteContact.website }, mainEntity: questions.map((item) => ({ "@type": "Question", name: item.q, acceptedAnswer: { "@type": "Answer", text: item.a } })) };
  return <main id="main-content" className="site-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><section className="page-hero"><div className="container"><p className="breadcrumb"><Link href="/">Home</Link> / Guides / Types of microgrids</p><p className="eyebrow"><span /> Plain-language guide</p><h1>Types of microgrids</h1><p className="page-lede">Microgrids are classified by the customers they serve, the reason they exist, their grid relationship, and the technologies inside them.</p></div></section><section className="content-section"><div className="container"><div className="definition-grid"><p className="section-index mono">THE SHORT ANSWER</p><div><p className="answer-copy">The major microgrid types are campus, community, island, remote, military, industrial, DC, and utility systems. Categories overlap: a military island base can be both a campus and a remote microgrid.</p></div></div><div className="archive-note">This guide modernizes the original Microgrid Projects taxonomy while preserving its central idea: microgrids are best understood by the job they are designed to do.</div><div className="guide-grid">{microgridTypes.map((type, index) => <article className="guide-card" id={type.slug} key={type.slug}><span className="mono">{String(index + 1).padStart(2, "0")}</span><h2>{type.name}</h2><p>{type.summary}</p><Link className="text-link" href={`/projects?sector=${encodeURIComponent(type.name.includes("Military") ? "Defense" : type.name.includes("Campus") ? "Campus & research" : type.name.includes("Island") || type.name.includes("Remote") ? "Island & remote community" : type.name.includes("Industrial") ? "Industrial & mining" : "")}`}>Browse related records <span aria-hidden="true">→</span></Link></article>)}</div><div className="faq-layout content-section"><div><p className="eyebrow eyebrow-dark"><span /> Quick answers</p><h2>Questions people ask about microgrid types</h2></div><div className="faq-list">{questions.map((item) => <details key={item.q}><summary>{item.q}<span aria-hidden="true">+</span></summary><p>{item.a}</p></details>)}</div></div></div></section></main>;
}
